from uuid import uuid4

from qdrant_client import QdrantClient
from qdrant_client.models import Distance, PointStruct, VectorParams


QDRANT_URL = "http://localhost:6333"
COLLECTION_NAME = "document_chunks"


qdrant_client = QdrantClient(url=QDRANT_URL)


def create_collection(vector_size: int) -> None:
    """Create the document collection if it does not already exist."""

    collections = qdrant_client.get_collections().collections
    existing_names = {collection.name for collection in collections}

    if COLLECTION_NAME in existing_names:
        return

    # Cosine similarity is useful for comparing the semantic direction
    # of text embeddings rather than their absolute magnitude.
    qdrant_client.create_collection(
        collection_name=COLLECTION_NAME,
        vectors_config=VectorParams(
            size=vector_size,
            distance=Distance.COSINE,
        ),
    )


def store_chunks(
    document_id: str,
    filename: str,
    chunks: list[str],
    embeddings: list[list[float]],
    chunking_strategy: str,
) -> None:
    """Store document chunks and their embeddings in Qdrant."""

    if len(chunks) != len(embeddings):
        raise ValueError(
            "Each chunk must have exactly one embedding."
        )

    if not chunks:
        return

    points = []

    for index, (chunk, embedding) in enumerate(
        zip(chunks, embeddings, strict=True)
    ):
        points.append(
            PointStruct(
                id=str(uuid4()),
                vector=embedding,
                payload={
                    "document_id": document_id,
                    "filename": filename,
                    "chunk_index": index,
                    "chunking_strategy": chunking_strategy,
                    "text": chunk,
                },
            )
        )

    qdrant_client.upsert(
        collection_name=COLLECTION_NAME,
        points=points,
    )

def search_chunks(
    query_embedding: list[float],
    limit: int = 5,
) -> list[dict]:
    """Search Qdrant for chunks most similar to a query embedding."""

    if not query_embedding:
        raise ValueError("Query embedding cannot be empty.")

    if limit <= 0:
        raise ValueError("limit must be greater than 0.")

    # The query embedding is generated by the same model used during
    # ingestion. Using the same embedding space is required for meaningful
    # similarity comparison between the question and stored document chunks.
    search_results = qdrant_client.query_points(
        collection_name=COLLECTION_NAME,
        query=query_embedding,
        limit=limit,
        with_payload=True,
    ).points

    results: list[dict] = []

    for result in search_results:
        # Qdrant's payload is optional — a point could theoretically be
        # stored without one. Fall back to an empty dict so the .get()
        # calls below never fail.
        payload = result.payload or {}

        results.append(
            {
                "score": result.score,
                "document_id": payload.get("document_id"),
                "filename": payload.get("filename"),
                "chunk_index": payload.get("chunk_index"),
                "chunking_strategy": payload.get("chunking_strategy"),
                "text": payload.get("text"),
            }
        )

    return results